[models]
codegen = "gpt-5"
postproc = "gpt-4o-mini"

[geo_codegen]
model = "gpt-5"
temperature = 0.0

[gen]
temperature = 1
max_tokens  = 4096

[postproc]
enabled     = true
max_loops = 3
temperature = 0.2
quality     = "-ql"        # 빠른 시도
timeout_sec = 40
